export const PERMISSIONS = {
    dashboardSidebar: 'dashboard.sidebar',
    dashboardView: 'dashboard.view',
    usersSidebar: 'users.sidebar',
    usersView: 'users.view',
    usersShow: 'users.show',
    usersCreate: 'users.create',
    usersUpdate: 'users.update',
    usersDelete: 'users.delete',
    permissionsSidebar: 'permissions.sidebar',
    permissionsView: 'permissions.view',
    permissionsCreate: 'permissions.create',
    permissionsUpdate: 'permissions.update',
    auditsSidebar: 'audits.sidebar',
    auditsView: 'audits.view',
} as const;
